### ISSUE TITLE
INSTALLATION FAILED

### ISSUE THREAD

**Issue by bloggingmastery** [vector-im/jitsi-helm#82]
Error: INSTALLATION FAILED: execution error at (jitsi/templates/web-deployment.yaml:8:23): One of PUBLIC_URL or ingress.hosts must be provided

some igress host error

please help me anybody

**Comment by Ufuck1903** [comment]
```
ingress:
  annotations: {}
  enabled: true
  extraLabels: {}
  extraPaths: []
  hosts: ["meet.example.com"] //Change this line
  ```
  
  Hopefully its helps
